LearnTogether/ViewModels/Layout.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;

namespace LearnTogether.ViewModels
{
    public class SidebarTag
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
        public string Slug { get; private set; }
        public int PostCount { get; private set; }

        public SidebarTag(int id, string name, string slug, int postCount)
        {
            Id = id;
            Name = name;
            Slug = slug;
            PostCount = postCount;
        }
    }

    public class LayoutSidebar
    {
        public bool IsLogedIn { get; set; }
        public string Username { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsModerator { get; set; }
        public IEnumerable<SidebarTag> Tags { get; set; }
    }
}

LearnTogether/Controllers/LayoutController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;
using LearnTogether.Models;
using LearnTogether.ViewModels;
using NHibernate.Linq;

namespace LearnTogether.Controllers
{
    public class LayoutController : Controller
    {
        //child action only allows action to be called only from the base view
        //it cannnot be called on its own
        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            return View(new LayoutSidebar
            {
                IsLogedIn = Auth.User != null,
                Username = Auth.User != null ? Auth.User.Username : "",
                IsAdmin = User.IsInRole("admin"),
                IsModerator = User.IsInRole("moderator"),
                Tags = Database.Session.Query<Tag>()
                .Select(tag => new
                {
                    tag.Id,
                    tag.Name,
                    tag.Slug,
                    PostCount = tag.Posts.Count
                }).Where(x => x.PostCount > 0)
                    .OrderByDescending(p => p.PostCount)
                    .Select(tag => new SidebarTag(tag.Id, tag.Name, tag.Slug, tag.PostCount)).ToList()
            });
        }
    }
}

LearnTogether/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using LearnTogether.ViewModels;
using NHibernate.Linq;
using LearnTogether.Models;
using LearnTogether.Infrastructure;
using NHibernate.Linq.Functions;
using Remotion.Linq.Utilities;

namespace LearnTogether.Controllers
{
    public class PostsController : Controller
    {
        private const int POSTS_PER_PAGE = 5;
        public ActionResult Index(int page = 1)  
        {
            var query = Database.Session.Query<Post>()
                .Where(x => x.DeletedAt == null)
                .OrderByDescending(x => x.CreatedAt);
            var totalPosts = query.Count();
            var ids = query.Skip((page - 1) * POSTS_PER_PAGE)
                .Take(POSTS_PER_PAGE)
                .Select(x => x.Id).ToArray();
            var posts = query.Where(x => ids.Contains(x.Id))
                .FetchMany(x => x.Tags)
                .Fetch(x => x.User)
                .ToList();
            return View(new PostsIndex {
                Posts = new PageData<Post>(posts, totalPosts, page, POSTS_PER_PAGE)
            });
        }

        public ActionResult Tag(string idAndSlug, int page = 1)
        {
            var parts = Separate(idAndSlug);
            if (parts == null)
                return HttpNotFound();
            var tag = Database.Session.Load<Tag>(parts.Item1);
            if (tag == null)
                return HttpNotFound();
            if(!tag.Slug.Equals(parts.Item2, StringComparison.CurrentCultureIgnoreCase))
            return RedirectToRoutePermanent("tag", new { id = parts.Item1, slug = tag.Slug});

            var totalPosts = tag.Posts.Count;
            var postsIds = tag.Posts.Skip((page - 1) * POSTS_PER_PAGE)
                .OrderByDescending(x => x.CreatedAt)
                .Take(POSTS_PER_PAGE)
                .Where(x => x.DeletedAt == null)
                .Select(x => x.Id)
                .ToArray();

            var posts = Database.Session.Query<Post>()
                .OrderByDescending(x => x.CreatedAt)
                .Where(x => postsIds.Contains(x.Id))
                .FetchMany(x => x.Tags)
                .Fetch(x => x.User)
                .ToList();

            return View(new PostsTag
            {
                Tag = tag,
                Posts = new PageData<Post>(posts, totalPosts, page, POSTS_PER_PAGE)
            });
        }

        public ActionResult Show(string idAndSlug)
        {
            var parts = Separate(idAndSlug);
            if (parts == null)
                return HttpNotFound();

            var post = Database.Session.Load<Post>(parts.Item1);
            if (post == null || post.IsDeleted)
                return HttpNotFound();

            if (!post.Slug.Equals(parts.Item2, StringComparison.CurrentCultureIgnoreCase))
                return RedirectToRoutePermanent("Post", new {id = parts.Item1, slug = post.Slug});

            return View(new PostsShow {Post = post});
        }

        private static Tuple<int, string> Separate(string idAndSlug)
        {
            //  starting ^
            //  openn group (
            // \d+ zero to many didgits 
            //  \- escape 
            // another group any character  (.*)
            // $ end
            var matches = Regex.Match(idAndSlug, @"^(\d+)\-(.*)?$");
            if (!matches.Success)
                return null;
            var id = int.Parse(matches.Result(("$1")));
            var sluug = matches.Result("$2");
            return Tuple.Create(id, sluug);
        }
    }
}

LearnTogether/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - LearnTogether</title>
    @Styles.Render("~/styles")
</head>
<body>

    <div class="site-header">
        <header class="container">
            <h1 class="page-header">
                <a href="@Url.RouteUrl("Home")">
                    Learn Together
                </a>
                <small>Sharing is caring!!!</small>
            </h1>
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="@Url.RouteUrl("Home")"> <span class="glyphicon glyphicon-home"></span>  Home</a></li>

                            <li><a href="#">Page 1</a></li>
                            <li><a href="#">Page 2</a></li>
                            <li><a> <span class="glyphicon glyphicon-envelope"></span>  Contact Us</a></li>

                            @if (User.IsInRole("admin"))
                            {
                                <li>
                                    <a href="@Url.Action("index", "Posts", new {area = "admin"})"><span class="glyphicon glyphicon-user"></span> Admin View</a>
                                </li>
                            }
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="@Url.RouteUrl("logout")"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="@Url.RouteUrl("Home")"> <span class="glyphicon glyphicon-home"></span>   Home</a></li>

                            <li><a href="#">Page 1</a></li>
                            <li><a href="#">Page 2</a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-envelope"></span>  Contact Us</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                            <li><a href="@Url.RouteUrl("login")"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                        </ul>
                    }
                </div>
            </nav>

        </header>

    </div>

    <div class="container">

        <div class="row">

            @if (User.Identity.IsAuthenticated)
            {
                <div class="col-lg-8 content">
                    @RenderBody()
                </div>
                <div class="col-lg-4 sidebar">
                    @Html.Action("sidebar", "Layout")
                </div>
            }
            else
            {
                <div class="col-lg-12 content">
                    @RenderBody()
                </div>
            }

        </div>
        <footer> &copy; @DateTime.UtcNow.Year <small>Learn Togeter by : Gediminas Valevicius</small></footer>
    </div>

    @Scripts.Render("~/scripts")
    @RenderSection("Scripts", false)

</body>
</html>